### ISSUE TITLE
SHEX::reset() is incompatible with ctor

### ISSUE THREAD

**Issue by brewmanz** [RobTillaart/SHEX#6]
I haven't used it, but looking at SHEX::reset(), it sets `_length    = 0;`
This is different behaviour to the ctor.
I suggest adding `uint8_t length = 16` to the function's signature, to more closely mimic how ctor works

Whilst you're there, maybe add `#define SHEX_DEFAULT_LENGTH 16` and use that as the default.

**Comment by RobTillaart** [comment]
Thanks for the issue, might rake a few days.
Although this one seems straightforward.

**Comment by RobTillaart** [comment]
Started with a 0.2.2 version to fix this.

- fix should also be default param for ```setBytesPerLine(const uint8_t length = SHEX_DEFAULT_LENGTH)```
- added ```#define SHEX_MAX_LENGTH                 32``` too  to remove magic number from code.
-
